[package]
title = "omni.ui Window Scatter"
description = "The full end to end example of the window"
version = "1.0.1"
category = "Scatter"
authors = ["Victor Yudin"]
repository = "https://gitlab-master.nvidia.com/omniverse/kit-extensions/kit-windows"
keywords = ["example", "window", "ui"]
changelog = "docs/CHANGELOG.md"
icon = "data/icon.png"
preview_image = "data/preview.png"

[dependencies]
"omni.ui" = {}
"omni.usd" = {}
"omni.kit.menu.utils" = {}

[[python.module]]
name = "omni.example.ui_scatter_tool"

[[test]]
args = [
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--no-window"
]
dependencies = [
    "omni.kit.renderer.core",
    "omni.kit.renderer.capture",
]
